### ISSUE TITLE
gif runs a lot faster

### ISSUE THREAD

**Issue by ktsaou** [phw/peek#190]
Hi,

thank you for peek!

I compiled the latest git version on fedora 26, and the recorded gifs run a lot faster.

In the following example, I tried to click once even second (check the second on the chart). As you can see, every time I clicked, peek fast forwarded it.

![peek 2017-10-11 00-52](https://user-images.githubusercontent.com/2662304/31412628-822e3f6e-ae1e-11e7-842d-93799ed8b8e7.gif)

In this version I clicked once every 5 seconds. It starts right, but then it runs a lot faster:

![peek 2017-10-11 00-57](https://user-images.githubusercontent.com/2662304/31412816-456a88d4-ae1f-11e7-92e4-b3839f60e30b.gif)

Then, in this version, I just moved the mouse, then stopped, then moved it again, and so on. Note that when the mouse stops, the gif runs faster, but while it moves it goes right:

![peek 2017-10-11 01-02](https://user-images.githubusercontent.com/2662304/31412987-f55043ce-ae1f-11e7-9b2e-39d68aca3f8f.gif)

**Comment by phw** [comment]
This is pretty strange, especially that it seems to be coupled to mouse actions. Can you try two things:

1. Try recording a WebM or MP4 file instead of a GIF (you can change this in the settings). This will tell us whether the behavior is in the recorded video or happens during conversion to GIF.

2. If you are using Gnome, try the ffmpeg recording backend. For this start first start Peek from command line, it will output which recording backend it is using (on Gnome it should show `gnome-shell`, otherwise `ffmpeg`). If gnome-shell is used, try

        peek -b ffmpeg

    and see if the issue is still reproducible.

**Comment by ktsaou** [comment]
Recording an MP4 does not work at all. It logs:

```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

Recording with `-b ffmpeg` produces garbage gifs:

![peek 2017-10-11 12-17](https://user-images.githubusercontent.com/2662304/31432119-6cae2734-ae7e-11e7-8fe7-4c43876bbd5e.gif)

This is the log:

```
$ peek -b ffmpeg
Requested screen recorder backend ffmpeg

(peek:12931): Gtk-WARNING **: Theme directory emoties/scalable of theme Uniform+ has no size field

ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags='-I/usr/include/nvenc ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, x11grab, from ':0+2660,390':
  Duration: N/A, start: 1507713428.824420, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 738x290, 10 fps, 10 tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> pam (native))
Press [q] to stop, [?] for help
Output #0, rawvideo, to '/home/costa/.cache/peek/peekXXXXXX.pam':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: pam, rgb24, 738x290, q=2-31, 200 kb/s, 10 fps, 10 tbn, 10 tbc
    Metadata:
      encoder         : Lavc57.89.100 pam
frame=  288 fps= 10 q=-0.0 Lsize=  180597kB time=00:00:28.80 bitrate=51369.8kbits/s speed=1.02x    
video:180597kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```

Recording without capturing the mouse, has the same effect. On this gif I was moving the mouse up to 12:20:54, then I stopped. As you can see it runs faster when I stopped:

![peek 2017-10-11 12-21](https://user-images.githubusercontent.com/2662304/31432291-ea291ffc-ae7e-11e7-92e7-864ed5c52c49.gif)

**Comment by ktsaou** [comment]
btw, fedora 26 runs on wayland, not X11. I don't know if this makes a difference.

**Comment by ktsaou** [comment]
Recording a WebM (without `-b ffmpeg`) does not have the issue. Timing seems right.

**Comment by phw** [comment]
> Recording an MP4 does not work at all.

You need `gstreamer1-plugins-ugly` installed for MP4, see https://github.com/phw/peek#fedora . But testing with WebM alone should be fine for this issue.

> btw, fedora 26 runs on wayland, not X11. I don't know if this makes a difference.

A huge one, in this case you are limited to the `gnome-shell` backend. Wayland does not allow arbitrary clients to capture other windows, as X does. Hence your result with only the mouse cursor.

The interesting results are, that WebM works without issue, but when recording a GIF the issue is still tied to mouse movement even if the mouse is not recorded. Do mouse actions outside the recording area also effect this?

At this time I suspect it is not actually the conversion from video to GIF, as this has no relationship to mouse actions, especially when the cursor is not even visible. So it must be the recorded video. For GIF recording a pretty large lossless video file gets recorded, maybe your system starts dropping frames because it gets too busy. Not sure why simple mouse movements should cause this, though. Do you see anything special in resource usage while recording? Maybe also check disk IO with `iotop`.

**Comment by ktsaou** [comment]
> You need gstreamer1-plugins-ugly installed for MP4

I just installed it. Same result (black gif with corrupted pointer movement).

> Do mouse actions outside the recording area also effect this?

Yes, it does not matter where the pointer is.

> maybe your system starts dropping frames because it gets too busy. Not sure why simple mouse movements should cause this, though. Do you see anything special in resource usage while recording? Maybe also check disk IO with iotop.

The system is totally idle. This is a high-end laptop (Dell XPS 9560, Core i7, 32GB RAM, 1TB SSD, kernel 4.13.4, fedora 26). I made all tests with just a web browser, a shell and peek open. It has a 4K HiDPI display, but I also made a few tests on an external HD monitor. Same result.

**Comment by ktsaou** [comment]
Switched to Xorg and tested it there too. It still happens. If the mouse pointer does not move, it goes faster.

**Comment by ktsaou** [comment]
btw, converting the webm file to gif, gives this output:

```
$ ffmpeg -i 'Peek 2017-10-11 13-59.webm' 'Peek 2017-10-11 13-59.gif'
ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags='-I/usr/include/nvenc ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, matroska,webm, from 'Peek 2017-10-11 13-59.webm':
  Metadata:
    encoder         : GStreamer matroskamux version 1.12.2
    creation_time   : 2017-10-11T10:59:36.000000Z
  Duration: 00:00:16.42, start: 0.005000, bitrate: 26 kb/s
    Stream #0:0(eng): Video: vp8, yuv420p(progressive), 738x290, SAR 1:1 DAR 369:145, 10 fps, 10 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      title           : Video
File 'Peek 2017-10-11 13-59.gif' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (vp8 (native) -> gif (native))
Press [q] to stop, [?] for help
[swscaler @ 0x5620f57bb700] No accelerated colorspace conversion found from yuv420p to bgr8.
Output #0, gif, to 'Peek 2017-10-11 13-59.gif':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0(eng): Video: gif, bgr8, 738x290 [SAR 1:1 DAR 369:145], q=2-31, 200 kb/s, 10 fps, 100 tbn, 10 tbc (default)
    Metadata:
      title           : Video
      encoder         : Lavc57.89.100 gif
Past duration 0.699989 too large
Past duration 0.879997 too large
Past duration 0.869987 too large
    Last message repeated 1 times
Past duration 0.699989 too large
Past duration 0.809990 too large
Past duration 0.979988 too large
Past duration 0.769997 too large
Past duration 0.999992 too large
Past duration 0.859993 too large
Past duration 0.669991 too large
Past duration 0.699989 too large
Past duration 0.859993 too large
Past duration 0.689995 too large
frame=   67 fps=0.0 q=-0.0 Lsize=     139kB time=00:00:16.31 bitrate=  69.9kbits/s dup=0 drop=2 speed= 147x    
video:138kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.947508%
```

I don't know if these `Past duration X too large` mean something for you. I am totally ignorant of this, but it could mean that the durations of a few frames are wrong.

**Comment by phw** [comment]
>> You need gstreamer1-plugins-ugly installed for MP4
> 
> I just installed it. Same result (black gif with corrupted pointer movement).

No, the black GIF happens when you try to record with ffmpeg backend, that just won't work on Wayland, you have to use X for that. gstreamer1-plugins-ugly is needed for recording MP4 with the gnome-shell backend.




> I don't know if these Past duration X too large mean something for you.

Maybe. Can you make this WebM available somewhere so I can test?

**Comment by ktsaou** [comment]
> Maybe. Can you make this WebM available somewhere so I can test?

Here it is: https://drive.google.com/file/d/0Byg-KnB4yqk6WElZSGZNVXNZaEE/view?usp=sharing

**Comment by ktsaou** [comment]
> gstreamer1-plugins-ugly is needed for recording MP4 with the gnome-shell backend.

You are right. MP4s do not have the timing issue either.
So, only GIFs and the mouse does not move.

**Comment by phw** [comment]
I tried two things:

1. I tried to reproduce this issue. Could have been nobody realized, since I mainly record short snippets where I constantly interact with mouse / keyboard or if not there is no animation that makes the speed up visible. But my self recorded GIFs have a constant speed no matter whether I move the mouse or not. I will later try to reproduce with Fedora 26

2. I tried converting your WebM file to a GIF with the same `convert` command Peek uses, but the result is fine. However, even in your WebM there is one small speedup at 13:49:46 . Could be framerate related, though.

One thing you could try is increase the framerate in settings. I mean for keeping the GIF size and processing time low it is really best to keep the framerate as low as possible, but for testing maybe it gives us a glue what is happening here.

**Comment by phw** [comment]
I just pushed some changes that remove the need to use ImageMagick for GIF generation and uses ffmpeg instead. This is actually something that could solve your issue here, too.

Can you try the latest github revision? As you are on Fedora the easiest way is probably to use the devel Flatpak from [peek-master.flatpakref](http://flatpak.uploadedlobster.com/peek-master.flatpakref) .

To run with ffmpeg GIF generation you have to set `PEEK_POSTPROCESSOR=ffmpeg`, so e.g. for the Flatpak version start it with:

    PEEK_POSTPROCESSOR=ffmpeg flatpak run com.uploadedlobster.peek

Or if you installed from source run `PEEK_POSTPROCESSOR=ffmpeg peek`.

**Comment by ktsaou** [comment]
Installed with:

```sh
flatpak install --user http://flatpak.uploadedlobster.com/peek-master.flatpakref
```

---

Run with:

```sh
$ flatpak run com.uploadedlobster.peek
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Using screen recorder backend gnome-shell
Recording to file /home/costa/.var/app/com.uploadedlobster.peek/cache/peek/peekFZEZ7Y.avi
```

The issue is still here:

![peek 2017-10-12 15-25](https://user-images.githubusercontent.com/2662304/31495805-afc1b53e-af61-11e7-81e3-f95c29649777.gif)

---

Run with:

```sh
$ PEEK_POSTPROCESSOR=ffmpeg flatpak run com.uploadedlobster.peek
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Using screen recorder backend gnome-shell
Recording to file /home/costa/.var/app/com.uploadedlobster.peek/cache/peek/peek05JV7Y.avi
ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.2.0 (GCC)
  configuration: --prefix=/app --disable-debug --disable-static --enable-gpl --enable-libvpx --enable-libx264 --enable-shared --enable-libxcb --enable-libxcb-xfixes --disable-libxcb-shape --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --disable-everything --enable-decoder=rawvideo --enable-decoder=png --enable-encoder=libx264 --enable-encoder=libvpx_vp8 --enable-encoder=rawvideo --enable-encoder=pam --enable-encoder=png --enable-encoder=gif --enable-demuxer=avi --enable-demuxer=image2 --enable-muxer=mp4 --enable-muxer=webm --enable-muxer=rawvideo --enable-muxer=gif --enable-muxer=image2 --enable-filter=crop --enable-filter=scale --enable-filter=fps --enable-filter=palettegen --enable-filter=paletteuse --enable-protocol=file --enable-indev=xcbgrab
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, avi, from '/home/costa/.var/app/com.uploadedlobster.peek/cache/peek/peek05JV7Y.avi':
  Duration: 00:00:15.20, start: 0.000000, bitrate: 68488 kb/s
    Stream #0:0: Video: rawvideo, bgra, 738x290, 68939 kb/s, 10 fps, 10 tbr, 10 tbn, 10 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to '/home/costa/.var/app/com.uploadedlobster.peek/cache/peek/peekREUN7Y.png':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: png, rgba, 16x16 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 10 fps, 10 tbn, 10 tbc
    Metadata:
      encoder         : Lavc57.89.100 png
[Parsed_palettegen_1 @ 0x101d160] 255(+1) colors generated out of 3038 colors; ratio=0.083937
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.10 bitrate=N/A speed=0.487x    
video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.2.0 (GCC)
  configuration: --prefix=/app --disable-debug --disable-static --enable-gpl --enable-libvpx --enable-libx264 --enable-shared --enable-libxcb --enable-libxcb-xfixes --disable-libxcb-shape --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --disable-everything --enable-decoder=rawvideo --enable-decoder=png --enable-encoder=libx264 --enable-encoder=libvpx_vp8 --enable-encoder=rawvideo --enable-encoder=pam --enable-encoder=png --enable-encoder=gif --enable-demuxer=avi --enable-demuxer=image2 --enable-muxer=mp4 --enable-muxer=webm --enable-muxer=rawvideo --enable-muxer=gif --enable-muxer=image2 --enable-filter=crop --enable-filter=scale --enable-filter=fps --enable-filter=palettegen --enable-filter=paletteuse --enable-protocol=file --enable-indev=xcbgrab
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, avi, from '/home/costa/.var/app/com.uploadedlobster.peek/cache/peek/peek05JV7Y.avi':
  Duration: 00:00:15.20, start: 0.000000, bitrate: 68488 kb/s
    Stream #0:0: Video: rawvideo, bgra, 738x290, 68939 kb/s, 10 fps, 10 tbr, 10 tbn, 10 tbc
Input #1, image2, from '/home/costa/.var/app/com.uploadedlobster.peek/cache/peek/peekREUN7Y.png':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 198 kb/s
    Stream #1:0: Video: png, rgba(pc), 16x16 [SAR 1:1 DAR 1:1], 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (rawvideo) -> fps
  Stream #1:0 (png) -> paletteuse:palette
  paletteuse -> Stream #0:0 (gif)
Press [q] to stop, [?] for help
Output #0, gif, to '/home/costa/.var/app/com.uploadedlobster.peek/cache/peek/peekPEVH7Y.gif':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: gif, pal8, 738x290, q=2-31, 200 kb/s, 10 fps, 100 tbn, 10 tbc (default)
    Metadata:
      encoder         : Lavc57.89.100 gif
frame=  152 fps=141 q=-0.0 Lsize=     193kB time=00:00:15.11 bitrate= 104.7kbits/s speed=  14x    
video:191kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.030543%
```

Same result:

![peek 2017-10-12 15-27](https://user-images.githubusercontent.com/2662304/31495919-1211fc94-af62-11e7-97e1-0099d8fd22ac.gif)

**Comment by phw** [comment]
Ok, the last run is actually interesting, because it rules out ImageMagick as the point of failure.

So next steps:

1. I still need to try to reproduce this on Fedora 26. I have only a VM, though, so results might not be comparable.
2. I will push changes how the intermediate video file for GIF gets recorded in the next days. Those changes might make a difference.
3. If you could try again on X11 but with `-b ffmpeg` this would also help to narrow down the cause (if this works well it would mean gnome-shell recording is to blame)

And thanks a lot for all your debugging.

**Comment by ktsaou** [comment]
> If you could try again on X11 but with -b ffmpeg this would also help to narrow down the cause (if this works well it would mean gnome-shell recording is to blame)

Run on Xorg, with:

```
$ peek -b ffmpeg
Requested screen recorder backend ffmpeg

(peek:7371): Gtk-WARNING **: Theme directory emoties/scalable of theme Uniform+ has no size field

ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags='-I/usr/include/nvenc ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libcdio --enable-indev=jack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, x11grab, from ':0+2058,412':
  Duration: N/A, start: 1507814240.174216, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 738x290, 10 fps, 10 tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> pam (native))
Press [q] to stop, [?] for help
Output #0, rawvideo, to '/home/costa/.cache/peek/peekXYEZ7Y.pam':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: pam, rgb24, 738x290, q=2-31, 200 kb/s, 10 fps, 10 tbn, 10 tbc
    Metadata:
      encoder         : Lavc57.89.100 pam
frame=  317 fps= 10 q=-0.0 Lsize=  198782kB time=00:00:31.70 bitrate=51369.8kbits/s speed=1.02x    
video:198782kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```

This works perfectly!

![peek 2017-10-12 16-17](https://user-images.githubusercontent.com/2662304/31498116-d399ebe0-af69-11e7-9adc-83e72ba31074.gif)

**Comment by phw** [comment]
Thanks again, I had expected this. For me this looks like an issue with the GNOME Shell screen recording, but still not sure why this happens. I tried to reproduce this on both Fedora 25 and 26 without luck. I recorded GNOME system monitor as this updates periodically. Just to be sure: The issue is independent for you of the software that is recorded, right?

Next thing will be that I change the intermediate video format. Still looking into the best video codec to use for this with GStreamer. I want to use a compressed format to have smaller temp file sizes (currently it writes the raw video stream to disk, and that gets huge quickly), at the same time it must be high quality to avoid color palette issues in the final GIF. Also it should be available in free GStreamer packages and not require any non-free package.

**Comment by ktsaou** [comment]
> I tried to reproduce this on both Fedora 25 and 26 without luck.

It seems I can't reproduce it anymore either.
I updated both fedora and peek and I tried several times.
So it seems it has been fixed somehow...

One thing I would like to ask is this (probably related to flatpack):

When I start peek from an icon, I get this:

![screenshot from 2017-10-13 23-05-12](https://user-images.githubusercontent.com/2662304/31564296-fefc0938-b06a-11e7-9c1d-3d05dc9c593d.png)

But when I start it from a shell, I get this:

![screenshot from 2017-10-13 23-06-11](https://user-images.githubusercontent.com/2662304/31564336-1fd39f40-b06b-11e7-9d5b-a4b1b6dc67bf.png)

I see flatpack installed gnome 3.26:

```sh
$ flatpak list
Ref                                    Options     
com.uploadedlobster.peek/x86_64/master user,current
org.gnome.Platform/x86_64/3.26         user,runtime
```

I think the icon starts peek with gnome 3.26 (that's why the difference in colors).
But it seems I can't remove it:

```sh
$ flatpak uninstall com.uploadedlobster.peek/x86_64/master
error: com.uploadedlobster.peek master not installed

$ flatpak uninstall com.uploadedlobster.peek
error: com.uploadedlobster.peek master not installed

$ flatpak info com.uploadedlobster.peek
Ref: app/com.uploadedlobster.peek/x86_64/master
ID: com.uploadedlobster.peek
Arch: x86_64
Branch: master
Origin: com.uploadedlobster.peek-origin
Commit: 06f37685331cf8ce758589ab006dd4acde34af06797d8fcc7d8355b30e047446
Location: /home/costa/.local/share/flatpak/app/com.uploadedlobster.peek/x86_64/master/06f37685331cf8ce758589ab006dd4acde34af06797d8fcc7d8355b30e047446
Installed size: 9.6 MB
Runtime: org.gnome.Platform/x86_64/3.26
```

Any ideas how to uninstall it?

**Comment by phw** [comment]
Ok, I will close this issue then. As I said earlier this is or was likely an issue in Gnome Shell itself.

Regarding the Flatpak: The difference in look.is because Flatpak cannot use the GTK theme from your system, as themes are not compatible between GTK Versions. That's why by default all Flatpak apps use Adwaita. But some themes have been packaged as Flatpak addons in flathub.org, installing them allow Flatpak apps to use those themes.

For uninstalling you will need to use the `--user` switch, as this Flatpak was installed in user mode and not system wide:

    flatpak uninstall --user com.uploadedlobster.peek

**Comment by ktsaou** [comment]
Thank you!
