### ISSUE TITLE
Recent crashes when recording GIF on Fedora 30

### ISSUE THREAD

**Issue by orschiro** [phw/peek#453]
Hi guys, 

Not sure if this is Fedora 30 related but recently, Peek keeps crashing when recording GIFs.

1. I click STOP
2. It asks me where to save the file
3. For a moment, I see "Rendering" and then it crashes

Has anyone seen the same recently?

Thanks and regards

**Comment by davidakerr** [comment]
I have the same behaviour on Pop!_OS.  Mp4 works fine.

**Comment by agoose77** [comment]
I have the same issue on Ubuntu 19.04

**Comment by jayesh-bhoot** [comment]
In my case, crash occurs (after I stop recording, and hit on Save in Save File Dialog) if I am using gifski. Otherwise, peek renders the gif fine.
OS: Fedora 30
In case this matters, gifski was installed as a rust crate.

**Comment by jdemonasterio** [comment]
+1 on Ubuntu 19.04.

If it helps, running these lines for versions (no gifski):
```sh
gtk-launch --version
apt-cache policy libglib2.0-dev | egrep 'Installed|Candidate|glib2\.0'
apt-cache policy libkeybinder-3.0.0 | egrep 'Installed|Candidate|libkeybinder-3\.0\.0'
apt-cache policy gstreamer1.0-plugins-good | egrep 'Installed|Candidate|gstreamer'
ffmpeg -version
```

outputs

```sh
3.24.8
libglib2.0-dev:
  Installed: 2.60.4-0ubuntu0.19.04.1
  Candidate: 2.60.4-0ubuntu0.19.04.1
  Installed: 0.3.2-1
  Candidate: 0.3.2-1
gstreamer1.0-plugins-good:
  Installed: 1.15.90-1ubuntu1
  Candidate: 1.15.90-1ubuntu1
ffmpeg version 4.1.3-0ubuntu1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8 (Ubuntu 8.3.0-6ubuntu1)
```

**Comment by jdemonasterio** [comment]
ok @here , this issue might be a possible duplicate of https://github.com/phw/peek/issues/434
at least for us on Ubuntus. You might benefit from their proposed patches/workarounds.

**Comment by NatoBoram** [comment]
> ok `@here` , this issue might be a possible duplicate of #434
> at least for us on Ubuntus. You might benefit from their proposed patches/workarounds.

Which is possibly a duplicate of #419, which is closed by https://github.com/phw/peek/pull/449. Was the fix merged in distribution repos?

**Comment by tim77** [comment]
> Was the fix merged in distribution repos?

Fix merged 2 month ago, since 2019-06-23 in Fedora
https://bodhi.fedoraproject.org/updates/FEDORA-2019-565b2e2d6a

**Comment by Jared-Sprague** [comment]
I'm having the same issue still in Fedora 30 Kernel 5.2.15-200.  I dnf updated everything on Sep 20th 2019.  I'm only using default fedora repositories.  I tried Peek with both dnf install peek, and installing with Flatpack flatub method, but both crash after clicking stop while I'm on the save file menu.

**Comment by phw** [comment]
Duplicate of #419, fixed in 1.4 release

**Comment by tim77** [comment]
v1.4 already built and waiting for you karma.

- [F30](https://bodhi.fedoraproject.org/updates/FEDORA-2019-b00feeb9e0)
- [F31](https://bodhi.fedoraproject.org/updates/FEDORA-2019-072cd413c2)
